# Generated by Django 2.2 on 2020-01-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(default=0, max_length=120, unique=True)),
                ('first_name', models.CharField(default='', max_length=120)),
                ('last_name', models.CharField(default='', max_length=120)),
                ('employee_type', models.CharField(choices=[(1, 'Full Time'), (0, 'Part Time')], max_length=15)),
                ('date_of_birth', models.DateField()),
                ('date_of_membership', models.DateField()),
                ('address', models.CharField(default='', max_length=120)),
                ('city', models.CharField(default='', max_length=120)),
                ('province', models.CharField(choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island')], max_length=120)),
                ('contact_no', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[(1, 'Active'), (0, 'Inactive')], max_length=120)),
                ('email', models.EmailField(default='', max_length=120)),
                ('active', models.NullBooleanField()),
            ],
        ),
    ]
