# Generated by Django 2.2 on 2020-01-08 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='active',
        ),
    ]
