# Generated by Django 2.2 on 2020-01-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_core', '0003_auto_20200108_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
    ]
